### ISSUE TITLE
缺少rtea

### ISSUE THREAD

**Issue by geilige** [cscs181/CAI#34]
ModuleNotFoundError: No module named 'rtea'

**Comment by yanyongyu** [comment]
请确认你是否安装了 `rtea`

```bash
pip install rtea
```

**Comment by yanyongyu** [comment]
rtea目前只有mac linux windows的64位预编译版本，其余平台需要自行使用 `maturin` 编译安装

**Comment by geilige** [comment]
建议：pip freeze > requirements.txt

**Comment by yanyongyu** [comment]
。。。我并不清楚你是怎么安装的cai，本项目全部由`poetry`管理依赖，`pip`和`requirements.txt`已经是过时的东西了，具体请参考python包管理官方文档

```bash
poetry install
```

**Comment by geilige** [comment]
好的 感谢 确实没用过poetry 一直pip

**Comment by geilige** [comment]
大佬是否有交流群或者qq或者微信

**Comment by geilige** [comment]
还有cai是基于安卓qq哪个版本呢

**Comment by yanyongyu** [comment]
> 大佬是否有交流群或者qq或者微信

cai主页readme上有挂群号，但是没啥人

**Comment by yanyongyu** [comment]
> 还有cai是基于安卓qq哪个版本呢

可以参考[protocol.py](https://github.com/cscs181/CAI/blob/master/cai/settings/protocol.py)
